version: '3'

services:
  web:
    build:
      dockerfile: DockerFile
      context: .
    ports:
      - "8080:8080"
    environment:
    # this will set DB_HOST 
      - DB_HOST=mySQLDBservice
    depends_on:
      - mySQLDBservice
    command: npm start
  mySQLDBservice:
    image: mysql:latest
    volumes:
      - ${pwd}/server/db/schema/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dbname
      # other env variables https://hub.docker.com/_/mysql/



